# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Thoughts about thoughts
tagline:             'Random epiphanies'
description:         ''
url:                 http://ins0m.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Alexander Waldmann
  url:               https://wwwmatthes.in.tum.de/pages/n3pozdzwts1i/Alexander-Waldmann
  email:             waldmann@in.tum.de

# Custom vars
version:             1.0.0
